theme: jekyll-theme-cayman
title: The 6th International Workshop on Multi-Agent Path Finding
description: part of the 39th AAAI Conference on Artificial Intelligence (AAAI) 2025, Philadelphia, Pennsylvania, USA
github:
  is_project_page: false
