theme: jekyll-theme-cayman
title: The 6th International Workshop on Multi-Agent Path Finding
date: March 3, 2025
location: Philadelphia, Pennsylvania, USA
description: part of the 39th AAAI Conference on Artificial Intelligence (AAAI) 2025
submission_site:
  show: true
  url: https://cmt3.research.microsoft.com/WoMAPF2025/Submission/Index
plugins:
  - jekyll-sitemap
